# Header

menu:
  首页: /
  归档: /archives/
  分类: /categories
  关于: /about

logo: http://oe54phg1r.bkt.clouddn.com/blog/2017-07-26-075816.jpg

rss: /atom.xml

widgets:
- category
- tag

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root:

# Content

# 文章太长，截断按钮文字
excerpt_link: more
# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: '展开全文'

# 目录
# 目录设定：0-不显示目录； 1-文章对应的md文件里有toc:true属性，才有目录； 2-所有文章均显示目录
toc: 1
# 根据自己的习惯来设置，如果你的目录标题习惯有标号，置为true即可隐藏hexo重复的序号；否则置为false
toc_hide_index: true
# 目录为空时的提示
toc_empty_wording: '目录，不存在的…'

# 是否有快速回到顶部的按钮
top: true

# Miscellaneous
baidu_analytics: ''
# google_analytics: ''
favicon: http://oe54phg1r.bkt.clouddn.com/favicon32x32.ico

#你的头像url
avatar: http://oe54phg1r.bkt.clouddn.com/blog/2017-07-26-075816.jpg